app:
  name: "OpenDAX"
  domain: "app.local"
  subdomain: "www"
render_protect: false 
ssl:
  enabled: false    # Make sure to enable during deployment
  email: "support@example.com"
license:
  url: "https://www.openware.com/api/v2/tenko"
  key: "PASTE-KEY-HERE"
images:
  peatio: rubykube/peatio:2.3.43
  barong: rubykube/barong:2.3.36
  frontend: quay.io/openware/baseapp-lite:2.3.20 # Check on quay.io/openware for latest tags
  tower: quay.io/openware/tower-lite:2.3.130
  postmaster: quay.io/openware/postmaster:2.3.4
vendor:
  frontend: git@github.com:openware/baseapp.git
vault:
  mode: development
  token: changeme
database:
  host: db
  port: 3306
  user: root
  password: changeme
storage:
  provider: "Google"
  bucketName: "opendax-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "none"
  siteKey: "changeme"
  secretKey: "changeme"
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  - kind: deposit
    address: "changeme"
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    max_balance: 1000.0
    secret: changeme
terraform:
  provider: "gcp"
  credentials: "~/safe/opendax.json"
  project: "example-opendax"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "opendax-pro"
  db_name: "opendax-db"
  core_machine_type: "n1-standard-8"
  db_machine_type: "db-n1-standard-2"
  cryptonode_machine_type: "n1-standard-2"
  cryptonode_disk_size: "400"
  core_image: "debian-cloud/debian-9"
  bitcoind_image: "debian-cloud/debian-9"
  parity_image: "debian-cloud/debian-9"
bitcoind:
  rpcuser: admin
  rpcpassword: changeme
  network: mainnet
  rpcport: 18332
  port: 18333
parity:
  network: mainnet
  rpcport: 8545
  port: 30303
